DEFAULT_VIDEO_LANGS = ['en']

tts_dict = {
    'albanian': 'sqi',
    'amharic': 'amh',
    'arabic': 'ara',
    'armenian': 'hyw',
    'azerbaijani': 'az',
    'basque': 'eus',
    'bengali': 'ben',
    'bulgarian': 'bul',
    'catalan': 'cat',
    'cebuano': 'ceb',
    'chichewa': 'nya',
    'chinese': 'hak',
    'dutch': 'nld',
    'english': 'eng',
    'finnish': 'fin',
    'french': 'fra',
    'german': 'deu',
    'greek': 'ell',
    'gujarati': 'guj',
    'haitian creole': 'hat',
    'hausa': 'hau',
    'hebrew': 'heb',
    'hindi': 'hin',
    'hungarian': 'hun',
    'icelandic': 'isl',
    'indonesian': 'ind',
    'javanese': 'jav',
    'kannada': 'kan',
    'kazakh': 'kaz',
    'khmer': 'khm',
    'korean': 'kor',
    'kyrgyz': 'kir',
    'lao': 'lao',
    'latin': 'lat',
    'latvian': 'lav',
    'malagasy': 'mlg',
    'malay': 'zlm',
    'malayalam': 'mal',
    'marathi': 'mar',
    'mongolian': 'mon',
    'odia': 'ory',
    'persian': 'fas',
    'polish': 'pol',
    'portuguese': 'por',
    'punjabi': 'pan',
    'romanian': 'ron',
    'russian': 'rus',
    'samoan': 'smo',
    'shona': 'sna',
    'somali': 'som',
    'spanish': 'spa',
    'swahili': 'swh',
    'swedish': 'swe',
    'tajik': 'tgk',
    'tamil': 'tam',
    'telugu': 'tel',
    'thai': 'tha',
    'turkish': 'tur',
    'ukrainian': 'ukr',
    'vietnamese': 'vie',
    'welsh': 'cym',
    'yoruba': 'yor'
}

trans_dict = {
    'albanian': 'sq',
    'amharic': 'am',
    'arabic': 'ar',
    'armenian': 'hy',
    'azerbaijani': 'azb',
    'basque': 'eu',
    'bengali': 'bn',
    'bulgarian': 'bg',
    'catalan': 'ca',
    'cebuano': 'ceb',
    'chichewa': 'ny',
    'chinese': 'zh-tw',
    'dutch': 'nl',
    'english': 'en',
    'finnish': 'fi',
    'french': 'fr',
    'german': 'de',
    'greek': 'el',
    'gujarati': 'gu',
    'haitian creole': 'ht',
    'hausa': 'ha',
    'hebrew': 'he',
    'hindi': 'hi',
    'hungarian': 'hu',
    'icelandic': 'is',
    'indonesian': 'id',
    'javanese': 'jw',
    'kannada': 'kn',
    'kazakh': 'kk',
    'khmer': 'km',
    'korean': 'ko',
    'kyrgyz': 'ky',
    'lao': 'lo',
    'latin': 'la',
    'latvian': 'lv',
    'malagasy': 'mg',
    'malay': 'ms',
    'malayalam': 'ml',
    'marathi': 'mr',
    'mongolian': 'mn',
    'odia': 'or',
    'persian': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'punjabi': 'pa',
    'romanian': 'ro',
    'russian': 'ru',
    'samoan': 'sm',
    'shona': 'sn',
    'somali': 'so',
    'spanish': 'es',
    'swahili': 'sw',
    'swedish': 'sv',
    'tajik': 'tg',
    'tamil': 'ta',
    'telugu': 'te',
    'thai': 'th',
    'turkish': 'tr',
    'ukrainian': 'uk',
    'vietnamese': 'vi',
    'welsh': 'cy',
    'yoruba': 'yo'
}

def get_languages():
    return list(trans_dict.keys())

def is_valid_lang(language):
    languages = get_languages()
    return language.lower() in languages

def map_to_tts(code):
    return tts_dict[code.lower()]

def map_to_trans(code):
    return trans_dict[code.lower()]